# Generated by Django 6.0.2 on 2026-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='section',
            field=models.CharField(blank=True, help_text="Class section(s) assigned to this faculty, e.g. 'A', 'B', 'A & B'", max_length=100, null=True),
        ),
    ]
