# Generated by Django 6.0.2 on 2026-02-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_add_section_to_faculty_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, help_text="Class section assigned by admin (e.g. 'A', 'B'). Must match faculty section.", max_length=100, null=True),
        ),
    ]
